apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: vsphere-raw-block-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  
